2018-06-14 22:34:19,356 ERROR: Exception on /logout [GET] [in /home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/duan/Flask_microblog/app/routes.py", line 72, in logout
    HAHAlogout_user()
NameError: name 'HAHAlogout_user' is not defined
2018-06-14 22:34:22,627 ERROR: Exception on /logout [GET] [in /home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/duan/Flask_microblog/app/routes.py", line 72, in logout
    HAHAlogout_user()
NameError: name 'HAHAlogout_user' is not defined
2018-06-14 22:37:10,466 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:49]
2018-06-14 22:37:42,372 ERROR: Exception on /logout [GET] [in /home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/duan/Flask_microblog/app/routes.py", line 72, in logout
    HAHAlogout_user()
NameError: name 'HAHAlogout_user' is not defined
2018-06-16 00:01:18,658 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:51]
2018-06-16 00:03:03,048 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:51]
2018-06-16 16:07:59,185 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:51]
2018-06-16 16:09:26,189 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:51]
2018-06-16 16:19:27,855 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:51]
2018-06-16 16:37:32,122 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:51]
2018-06-16 16:38:28,361 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:51]
2018-06-16 16:44:18,742 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:51]
2018-06-16 16:45:27,474 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:51]
2018-06-17 12:45:01,974 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:51]
2018-06-18 23:19:42,060 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:51]
2018-06-19 17:17:53,481 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:51]
2018-06-19 22:54:55,395 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:53]
2018-06-19 22:55:44,406 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:53]
2018-06-19 23:03:47,400 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:53]
2018-06-20 21:41:11,131 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:55]
2018-06-21 11:08:06,084 INFO: Microblog startup [in /home/duan/Flask_microblog/app/__init__.py:56]
2018-06-21 11:08:17,726 ERROR: Exception on / [GET] [in /home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask_login/utils.py", line 260, in decorated_view
    return current_app.login_manager.unauthorized()
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask_login/login_manager.py", line 162, in unauthorized
    if self.login_message:
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask_babel/speaklater.py", line 26, in __len__
    return len(text_type(self))
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask_babel/speaklater.py", line 23, in __str__
    return text_type(self._func(*self._args, **self._kwargs))
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask_babel/__init__.py", line 552, in gettext
    t = get_translations()
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask_babel/__init__.py", line 227, in get_translations
    [get_locale()],
  File "/home/duan/.local/share/virtualenvs/Flask_microblog-6CoWjSse/lib/python3.6/site-packages/flask_babel/__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "/home/duan/Flask_microblog/app/__init__.py", line 62, in get_locale
    return request.accept_languages.best.match(app.config['LANGUAGES']) # compare list of langs requested by client against the supported langs of app, return best choice.
AttributeError: 'str' object has no attribute 'match'
